# Add the job name mapping
job_name_mapping = {
    "Accountants": "Accountants",
    "Adviseurs marketing, public relations en sales": "Adviseurs marketing,\nPR en sales",
    "Algemeen directeuren": "Algemeen\ndirecteuren",
    "Apothekersassistenten": "Apothekers\-\nassistenten",
    "Architecten": "Architecten",
    "Artsen": "Artsen",
    "Assemblagemedewerkers": "Assemblage\-\nmedewerkers",
    "Auteurs en taalkundigen": "Auteurs en\ntaalkundigen",
    "Automonteurs": "Automonteurs",
    "Bakkers": "Bakkers",
    "Bedieners mobiele machines": "Bedieners\nmobiele machines",
    "Bedrijfskundigen en organisatieadviseurs": "Bedrijfskundigen en\norganisatieadviseurs",
    "Beeldend kunstenaars": "Beeldend\nkunstenaars",
    "Beleidsadviseurs": "Beleids\-\nadviseurs",
    "Beroepsgroep sportinstructeurs": "Beroepsgroep\nsportinstructeurs",
    "Beveiligingspersoneel": "Beveiligings\-\npersoneel",
    "Bibliothecarissen en conservatoren": "Bibliothecarissen\nen conservatoren",
    "Biologen en natuurwetenschappers": "Biologen en\nnatuurwetenschappers",
    "Boekhouders": "Boekhouders",
    "Boekhoudkundig medewerkers": "Boekhoudkundig\nmedewerkers",
    "Bouwarbeiders afbouw": "Bouwarbeiders\nafbouw",
    "Bouwarbeiders ruwbouw": "Bouwarbeiders\nruwbouw",
    "Buschauffeurs en trambestuurders": "Buschauffeurs en\ntrambestuurders",
    "Callcentermedewerkers outbound en overige verkopers": "Callcenter\-\nmedewerkers\noutbound",
    "Chauffeurs auto's, taxi's en bestelwagens": "Chauffeurs auto's,\ntaxi's en bestelwagens",
    "Conciërges en teamleiders schoonmaak": "Conciërges en\nteamleiders schoonmaak",
    "Databank- en netwerkspecialisten": "Databank\- en\nnetwerkspecialisten",
    "Dekofficieren en piloten": "Dekofficieren\nen piloten",
    "Directiesecretaresses": "Directie\-\nsecretaresses",
    "Docenten algemene vakken secundair onderwijs": "Docenten algemene\nvakken VO",
    "Docenten beroepsgerichte vakken secundair onderwijs": "Docenten\nberoepsgerichte\nvakken VO",
    "Docenten hoger onderwijs en hoogleraren": "Docenten HO en\nhoogleraren",
    "Elektriciens en elektronicamonteurs": "Elektriciens en\nelektronicamonteurs",
    "Elektrotechnisch ingenieurs": "Elektrotechnisch\ningenieurs",
    "Financieel specialisten en economen": "Financieel\nspecialisten en\neconomen",
    "Fotografen en interieurontwerpers": "Fotografen en\ninterieurontwerpers",
    "Fysiotherapeuten": "Fysiotherapeuten",
    "Gebruikersondersteuning ICT": "Gebruikers\-\nondersteuning ICT",
    "Gespecialiseerd verpleegkundigen": "Gespecialiseerd\nverpleegkundigen",
    "Grafisch vormgevers en productontwerpers": "Grafisch vormgevers\nen ontwerpers",
    "Hoveniers, tuinders en kwekers": "Hoveniers,\ntuinders en kwekers",
    "Hulpkrachten bouw en industrie": "Hulpkrachten\nbouw en industrie",
    "Hulpkrachten landbouw": "Hulpkrachten\nlandbouw",
    "Ingenieurs (geen elektrotechniek)": "Ingenieurs\n(niet elektro)",
    "Journalisten": "Journalisten",
    "Juristen": "Juristen",
    "Kappers en schoonheidsspecialisten": "Kappers en\nschoonheidsspec.",
    "Kassamedewerkers": "Kassa\-\nmedewerkers",
    "Kelners en barpersoneel": "Kelners en\nbarpersoneel",
    "Keukenhulpen": "Keukenhulpen",
    "Koks": "Koks",
    "Laboranten": "Laboranten",
    "Laders, lossers en vakkenvullers": "Laders, lossers\nen vakkenvullers",
    "Land- en bosbouwers": "Land\- en\nbosbouwers",
    "Lassers en plaatwerkers": "Lassers en\nplaatwerkers",
    "Leerkrachten basisonderwijs": "Leerkrachten\nbasisonderwijs",
    "Leidsters kinderopvang en onderwijsassistenten": "Leidsters kinderopvang\nen onderwijsassist.",
    "Loodgieters en pijpfitters": "Loodgieters en\npijpfitters",
    "Maatschappelijk werkers": "Maatschappelijk\nwerkers",
    "Machinemonteurs": "Machine\-\nmonteurs",
    "Managers ICT": "Managers ICT",
    "Managers commerciële en persoonlijke dienstverlening": "Managers comm. en\npers. diensten",
    "Managers detail- en groothandel": "Managers detail\-\nen groothandel",
    "Managers gespecialiseerde dienstverlening": "Managers gespec.\ndienstverlening",
    "Managers horeca": "Managers horeca",
    "Managers logistiek": "Managers logistiek",
    "Managers onderwijs": "Managers\nonderwijs",
    "Managers productie": "Managers\nproductie",
    "Managers verkoop en marketing": "Managers verkoop\nen marketing",
    "Managers zakelijke en administratieve dienstverlening": "Managers zakelijke\nen admin. diensten",
    "Managers zonder specificatie": "Managers zonder\nspecificatie",
    "Managers zorginstellingen": "Managers\nzorginstellingen",
    "Medewerkers drukkerij en kunstnijverheid": "Medewerkers\ndrukkerij en kunst",
    "Medisch praktijkassistenten": "Medisch praktijk\-\nassistenten",
    "Medisch vakspecialisten": "Medisch\nvakspecialisten",
    "Metaalbewerkers en constructiewerkers": "Metaalbewerkers en\nconstructiewerkers",
    "Meubelmakers, kleermakers en stoffeerders": "Meubelmakers en\nstoffeerders",
    "Militairen": "Militairen",
    "Onderwijskundigen en overige docenten": "Onderwijskundigen\nen overige docenten",
    "Overheidsambtenaren": "Overheids\-\nambtenaren",
    "Overheidsbestuurders": "Overheids\-\nbestuurders",
    "Politie en brandweer": "Politie en\nbrandweer",
    "Politie-inspecteurs": "Politie\-\ninspecteurs",
    "Procesoperators": "Proces\-\noperators",
    "Productcontroleurs": "Product\-\ncontroleurs",
    "Productieleiders industrie en bouw": "Productieleiders\nindustrie en bouw",
    "Productiemachinebedieners": "Productie\-\nmachinebedieners",
    "Psychologen en sociologen": "Psychologen en\nsociologen",
    "Radio- en televisietechnici": "Radio\- en\ntelevisietechnici",
    "Receptionisten en telefonisten": "Receptionisten en\ntelefonisten",
    "Reisbegeleiders": "Reisbegeleiders",
    "Schilders en metaalspuiters": "Schilders en\nmetaalspuiters",
    "Schoonmakers": "Schoonmakers",
    "Secretaresses en administratief medewerkers": "Secretaresses en\nadmin. medewerkers",
    "Slagers": "Slagers",
    "Sociaal werkers, groeps- en woonbegeleiders": "Sociaal werkers en\nwoonbegeleiders",
    "Software- en applicatieontwikkelaars": "Software\- en\napp\-ontwikkelaars",
    "Specialisten personeels- en loopbaanontwikkeling": "Specialisten HR en\nloopbaanontw.",
    "Technici bouwkunde en natuur": "Technici bouwkunde\nen natuur",
    "Timmerlieden": "Timmerlieden",
    "Transportplanners en logistiek medewerkers": "Transportplanners en\nlogistiek medew.",
    "Uitvoerend kunstenaars": "Uitvoerend\nkunstenaars",
    "Veetelers": "Veetelers",
    "Verkoopmedewerkers detailhandel": "Verkoop\-\nmedewerkers\ndetailhandel",
    "Verpleegkundigen (mbo)": "Verpleegkundigen\n(mbo)",
    "Vertegenwoordigers en inkopers": "Vertegenwoordigers\nen inkopers",
    "Verzorgenden en verleners van overige persoonlijke diensten": "Verzorgenden en\noverige pers. diensten",
    "Vrachtwagenchauffeurs": "Vrachtwagen\-\nchauffeurs",
    "Vuilnisophalers en dagbladenbezorgers": "Vuilnisophalers en\ndagbladenbezorgers",
    "Winkeliers en teamleiders detailhandel": "Winkeliers en\nteamleiders detail",
    "Zakelijke dienstverleners": "Zakelijke\ndienstverleners"
}

job_names = ['Accountants',
'Adviseurs marketing, public relations en sales',
'Algemeen directeuren',
'Apothekersassistenten',
'Architecten',
'Artsen',
'Assemblagemedewerkers',
'Auteurs en taalkundigen',
'Automonteurs',
'Bakkers',
'Bedieners mobiele machines',
'Bedrijfskundigen en organisatieadviseurs',
'Beeldend kunstenaars',
'Beleidsadviseurs',
'Beroepsgroep sportinstructeurs',
'Beveiligingspersoneel',
'Bibliothecarissen en conservatoren',
'Biologen en natuurwetenschappers',
'Boekhouders',
'Boekhoudkundig medewerkers',
'Bouwarbeiders afbouw',
'Bouwarbeiders ruwbouw',
'Buschauffeurs en trambestuurders',
'Callcentermedewerkers outbound en overige verkopers',
"Chauffeurs auto's, taxi's en bestelwagens",
'Conciërges en teamleiders schoonmaak',
'Databank- en netwerkspecialisten',
'Dekofficieren en piloten',
'Directiesecretaresses',
'Docenten algemene vakken secundair onderwijs',
'Docenten beroepsgerichte vakken secundair onderwijs',
'Docenten hoger onderwijs en hoogleraren',
'Elektriciens en elektronicamonteurs',
'Elektrotechnisch ingenieurs',
'Financieel specialisten en economen',
'Fotografen en interieurontwerpers',
'Fysiotherapeuten',
'Gebruikersondersteuning ICT',
'Gespecialiseerd verpleegkundigen',
'Grafisch vormgevers en productontwerpers',
'Hoveniers, tuinders en kwekers',
'Hulpkrachten bouw en industrie',
'Hulpkrachten landbouw',
'Ingenieurs (geen elektrotechniek)',
'Journalisten',
'Juristen',
'Kappers en schoonheidsspecialisten',
'Kassamedewerkers',
'Kelners en barpersoneel',
'Keukenhulpen',
'Koks',
'Laboranten',
'Laders, lossers en vakkenvullers',
'Land- en bosbouwers',
'Lassers en plaatwerkers',
'Leerkrachten basisonderwijs',
'Leidsters kinderopvang en onderwijsassistenten',
'Loodgieters en pijpfitters',
'Maatschappelijk werkers',
'Machinemonteurs',
'Managers ICT',
'Managers commerciële en persoonlijke dienstverlening',
'Managers detail- en groothandel',
'Managers gespecialiseerde dienstverlening',
'Managers horeca',
'Managers logistiek',
'Managers onderwijs',
'Managers productie',
'Managers verkoop en marketing',
'Managers zakelijke en administratieve dienstverlening',
'Managers zonder specificatie',
'Managers zorginstellingen',
'Medewerkers drukkerij en kunstnijverheid',
'Medisch praktijkassistenten',
'Medisch vakspecialisten',
'Metaalbewerkers en constructiewerkers',
'Meubelmakers, kleermakers en stoffeerders',
'Militairen',
'Onderwijskundigen en overige docenten',
'Overheidsambtenaren',
'Overheidsbestuurders',
'Politie en brandweer',
'Politie-inspecteurs',
'Procesoperators',
'Productcontroleurs',
'Productieleiders industrie en bouw',
'Productiemachinebedieners',
'Psychologen en sociologen',
'Radio- en televisietechnici',
'Receptionisten en telefonisten',
'Reisbegeleiders',
'Schilders en metaalspuiters',
'Schoonmakers',
'Secretaresses en administratief medewerkers',
'Slagers',
'Sociaal werkers, groeps- en woonbegeleiders',
'Software- en applicatieontwikkelaars',
'Specialisten personeels- en loopbaanontwikkeling',
'Technici bouwkunde en natuur',
'Timmerlieden',
'Transportplanners en logistiek medewerkers',
'Uitvoerend kunstenaars',
'Veetelers',
'Verkoopmedewerkers detailhandel',
'Verpleegkundigen (mbo)',
'Vertegenwoordigers en inkopers',
'Verzorgenden en verleners van overige persoonlijke diensten',
'Vrachtwagenchauffeurs',
'Vuilnisophalers en dagbladenbezorgers',
'Winkeliers en teamleiders detailhandel',
'Zakelijke dienstverleners']